version: "3.9"
services:
  # server:
  #   build: ./server
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - ./server:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
    # depends_on:
    #   - server
